config/routes.rb
NestedForms::Application.routes.draw do
  resources :room_categories

  resources :hotels

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  has_many :room_categories, dependent: :destroy
  attr_accessible :name, :room_categories_attributes
  accepts_nested_attributes_for :room_categories,
                                reject_if: proc { |attributes| attributes['name'].blank? },
                                allow_destroy: true

  validates :name,
            presence: true
  def to_s
    name
  end
end

app/models/room_category.rb
class RoomCategory < ActiveRecord::Base
  belongs_to :hotel

  attr_accessible :name, :_destroy

  validates :name,
            presence: true
  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hotels }
    end
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/new
  # GET /hotels/new.json
  def new
    @hotel = Hotel.new
    @hotel.room_categories.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/1/edit
  def edit
    @hotel = Hotel.find(params[:id])
    @hotel.room_categories.build
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(params[:hotel])

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render json: @hotel, status: :created, location: @hotel }
      else
        format.html { render action: "new" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hotels/1
  # PUT /hotels/1.json
  def update
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      if @hotel.update_attributes(params[:hotel])
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/room_categories_controller.rb
class RoomCategoriesController < ApplicationController
  # GET /room_categories
  # GET /room_categories.json
  def index
    @room_categories = RoomCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @room_categories }
    end
  end

  # GET /room_categories/1
  # GET /room_categories/1.json
  def show
    @room_category = RoomCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room_category }
    end
  end

  # GET /room_categories/new
  # GET /room_categories/new.json
  def new
    @room_category = RoomCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room_category }
    end
  end

  # GET /room_categories/1/edit
  def edit
    @room_category = RoomCategory.find(params[:id])
  end

  # POST /room_categories
  # POST /room_categories.json
  def create
    @room_category = RoomCategory.new(params[:room_category])

    respond_to do |format|
      if @room_category.save
        format.html { redirect_to @room_category, notice: 'Room category was successfully created.' }
        format.json { render json: @room_category, status: :created, location: @room_category }
      else
        format.html { render action: "new" }
        format.json { render json: @room_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /room_categories/1
  # PUT /room_categories/1.json
  def update
    @room_category = RoomCategory.find(params[:id])

    respond_to do |format|
      if @room_category.update_attributes(params[:room_category])
        format.html { redirect_to @room_category, notice: 'Room category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /room_categories/1
  # DELETE /room_categories/1.json
  def destroy
    @room_category = RoomCategory.find(params[:id])
    @room_category.destroy

    respond_to do |format|
      format.html { redirect_to room_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/room_categories_helper.rb
module RoomCategoriesHelper
end

app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <h2>Room Categories</h2>
  <%= f.fields_for :room_categories do |room_category| %>
  <div class="room_category_fields" id="room_category_groups">
    <div class="field room_group" id="hotel_room_categories_attributes_0">
      <%= room_category.label :name %><br>
      <%= room_category.text_field :name %>
      <%#= room_category.check_box :_destroy %>
      <%#= room_category.label :_destroy, 'remove' %>
    </div>

    <a href="#" onclick="addMore();">Add Another</a>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>




<br><br><br>

<div id="groups">
    <div class='more_group' id="post_relics_attributes_0">
        <div class='photo'> <a data-toggle="upload" href="#">Insert photo</a>

            <input accept="image/*" id="post_relics_attributes_0_photo" name="post_relics_attributes_0_photo" type="file" />
        </div>
        <div class='fields'>
            <label for="post_relics_attributes_0_title">Title</label>
            <input id="post_relics_attributes_0_title" name="post_relics_attributes_0_title" type="text" value="" />
            <label for="post_relics_attributes_0_description">Description</label>
            <input id="post_relics_attributes_0_description" name="post_relics_attributes_0_description" type="text" value="" />
        </div>
        <input id="post_relics_attributes_0_id" name="post_relics_attributes_0_id" type="hidden" value="6" />
    </div>
    <div class='more_group' id="post_relics_attributes_1">
        <div class='photo'> <a data-toggle="upload" href="#">Insert photo</a>

            <input accept="image/*" id="post_relics_attributes_1_photo" name="post_relics_attributes_1_photo" type="file" />
        </div>
        <div class='fields'>
            <label for="post_relics_attributes_1_title">Title</label>
            <input id="post_relics_attributes_1_title" name="post_relics_attributes_1_title" type="text" />
            <label for="post_relics_attributes_1_description">Description</label>
            <input id="post_relics_attributes_1_description" name="post_relics_attributes_1_description" type="text" />
        </div>
        <input id="post_relics_attributes_1_id" name="post_relics_attributes_1_id" type="hidden" />
    </div>
</div>
<button onclick="addMoreEx();">Add Another</button>

<br><br><br>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<h1>Listing hotels</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hotels.each do |hotel| %>
  <tr>
    <td><%= hotel.name %></td>
    <td><%= link_to 'Show', hotel %></td>
    <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
    <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hotel', new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>
<p>
<strong>Name:</strong>
<%= @hotel.name %>
</p>
<h2>Room Categories</h2>
<% if @hotel.room_categories.any? %>
<ul>
<% @hotel.room_categories.each do |room_category| %>
<li><%= link_to room_category, room_category %></li>
<% end %>
</ul>
<% else %>
<p>none available</p>
<% end %>
<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedForms</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/room_categories/_form.html.erb
<%= form_for(@room_category) do |f| %>
  <% if @room_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room_category.errors.count, "error") %> prohibited this room_category from being saved:</h2>

      <ul>
      <% @room_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hotel %><br />
    <%= f.text_field :hotel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/room_categories/edit.html.erb
<h1>Editing room_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @room_category %> |
<%= link_to 'Back', room_categories_path %>

app/views/room_categories/index.html.erb
<h1>Listing room_categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Hotel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @room_categories.each do |room_category| %>
  <tr>
    <td><%= room_category.name %></td>
    <td><%= room_category.hotel %></td>
    <td><%= link_to 'Show', room_category %></td>
    <td><%= link_to 'Edit', edit_room_category_path(room_category) %></td>
    <td><%= link_to 'Destroy', room_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Room category', new_room_category_path %>

app/views/room_categories/new.html.erb
<h1>New room_category</h1>

<%= render 'form' %>

<%= link_to 'Back', room_categories_path %>

app/views/room_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @room_category.name %>
</p>

<p>
  <b>Hotel:</b>
  <%= @room_category.hotel %>
</p>


<%= link_to 'Edit', edit_room_category_path(@room_category) %> |
<%= link_to 'Back', room_categories_path %>